apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "resolver.fullname" . }}
  labels:
    {{- include "resolver.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "resolver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "resolver.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: {{ include "resolver.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          env:
            - name: MEMCACHED
              value: "{{ .Release.Name }}-memcached"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
