{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resolver.serviceAccountName" . }}
  labels:
{{ include "resolver.labels" . | nindent 4 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "resolver.serviceAccountName" . }}
  labels:
{{ include "resolver.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "resolver.serviceAccountName" . }}
  labels:
{{ include "resolver.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "resolver.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "resolver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
