FROM golang:1.13-alpine as builder

# Install libpcap and gcc
RUN apk add --update gcc libpcap-dev libc-dev && rm -rf /var/cache/apk/*

WORKDIR /app

copy . .

# Build application
RUN go get -d -v ./...
RUN go build cmd/insight/insight.go


# Generate a smaller docker image without build dependencies
FROM alpine:3.11

RUN apk add --update libpcap && rm -rf /var/cache/apk/*

COPY --from=builder /app/insight /insight
ENTRYPOINT ["/insight"]
