apiVersion: v1
kind: ConfigMap
metadata:
  # name: {{ include "configs.fullname" . }}-logstash
  name: insight-configs-logstash
  labels:
    {{- include "configs.labels" . | nindent 4 }}
data:
  insight.conf: |-
{{ .Files.Get "insight.conf" | indent 4 }}
  insight.template.json: |-
{{ .Files.Get "insight.template.json" | indent 4 }}
  extract_first_array_element.rb: |-
{{ .Files.Get "extract_first_array_element.rb" | indent 4 }}
