{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "probeinject.serviceAccountName" . }}
  labels:
{{ include "probeinject.labels" . | nindent 4 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "probeinject.serviceAccountName" . }}
  labels:
{{ include "probeinject.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - replicasets
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "probeinject.serviceAccountName" . }}
  labels:
{{ include "probeinject.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "probeinject.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "probeinject.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
