apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.kubestatestore.serviceName }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
